### PR TITLE
cleanup/rename alot; ensure that everything is loadable from api/json

### PR DESCRIPTION
**Pull request by Icehunter**
This is going to beat the hell out of updates on dependencies...

I'll need another PR to change naming scheme of plugin interface for ffxivapp. Third parties should have less to do as they won't be using the plugin interface and instead using the results of this.

Big changes:
* namespace/filename/class name changes
* Removed/New Xs are not cloned dictionaries so you don't just have the ID of something removed but all data it held before it was removed.
* various fixes for performance/comparisons/etc

### CODE REVIEW

**Comment by Icehunter** [comment]
@cjmanca I won't merge this until the API/and github repo's with json are appropriately updated. This is a manual optin update so it's going to have updated documentation and also require rethinking of the API. I've bumped it from V5 -> V6 to indicate it's breaking.

**Comment by Icehunter** [comment]
@ravahn @roxaskeyheart @namidairo @viion Adding you as well.

**Comment by vekien** [comment]
Is this just a clean up or does it actually change how it is used and any of it's functionality? Ever though of putting the schema API on github for easier management?

**Comment by Icehunter** [comment]
API Schema? The json files are on github in 2 different repo's; I just read those in from a webservice and use that so I have caching available and don't hit github limits.

icehunter/sharlayan-structures
icehunter/sharlayan-signatures

**Comment by vekien** [comment]
Would you hit github limits? There are lots of sites running on github that also feed json for adhoc API's. If the module was changed to read from github instead you also wouldn't need to keep a site running.

**Comment by Icehunter** [comment]
This is true... I should just copy out the html from the wordpress site by viewing it in the browser and save that to github pages ;) What is the suggestion for these endpoints:

https://xivapp.com/api/docs

zones, statuses, actions

They take XIVDB api's and transform the data into sharlayan data contracts.

**Comment by vekien** [comment]
Either I could supply a route that does the transformation for you (then anyone can just open the url and download the latest contracts), otherwise I am not too sure without providing some tool to do it.

**Pull request merged**
